### Dependencies

In [1]:
import pandas as pd
import numpy as np
import os
import csv

### File setup

In [2]:
# Data to load (csv)
input_data_file = os.path.join('..', 'resources', 'raw-stats-data.csv')

# Data to export (csv)
output_data_file = os.path.join('..', 'resources', 'clean-stats-data.csv')

### Extract CSV into dataframe

In [3]:
stats_df = pd.read_csv(input_data_file)
stats_df.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

### Transform stats dataframe

In [4]:
# Check number of rows in df
stats_df.shape

(800, 13)

In [5]:
# Create variable with TRUE if generation is equal to 1
gen_1 = stats_df['Generation'] == 1

# Create a filtered dataframe for only generation 1 pokemon
stats_transformed = stats_df[gen_1].copy()

# Check num of rows for filtered df
stats_transformed.shape

(166, 13)

In [6]:
# Get a list of columns
cols = list(stats_transformed)
cols

['#',
 'Name',
 'Type 1',
 'Type 2',
 'Total',
 'HP',
 'Attack',
 'Defense',
 'Sp. Atk',
 'Sp. Def',
 'Speed',
 'Generation',
 'Legendary']

In [7]:
# Move 'name' column to head of table using index, pop and insert
cols.insert(0, cols.pop(cols.index('Name')))

# Check list
cols

['Name',
 '#',
 'Type 1',
 'Type 2',
 'Total',
 'HP',
 'Attack',
 'Defense',
 'Sp. Atk',
 'Sp. Def',
 'Speed',
 'Generation',
 'Legendary']

In [8]:
# Use ix to reorder dataframe
stats_transformed = stats_transformed.ix[:, cols]
stats_transformed

/Users/bbobba/anaconda3/envs/datascience/lib/python3.6/site-packages/ipykernel_launcher.py:2: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated

,Name,#,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,Bulbasaur,1,Grass,Poison,318,45,49,49,65,65,45,1,False
1,Ivysaur,2,Grass,Poison,405,60,62,63,80,80,60,1,False
2,Venusaur,3,Grass,Poison,525,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,3,Grass,Poison,625,80,100,123,122,120,80,1,False
4,Charmander,4,Fire,NaN,309,39,52,43,60,50,65,1,False
5,Charmeleon,5,Fire,NaN,405,58,64,58,80,65,80,1,False
6,Charizard,6,Fire,Flying,534,78,84,78,109,85,100,1,False
7,CharizardMega Charizard X,6,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,CharizardMega Charizard Y,6,Fire,Flying,634,78,104,78,159,115,100,1,False
9,Squirtle,7,Water,NaN,314,44,48,65,50,64,43,1,False
10,Wartortle,8,Water,NaN,405,59,63,80,65,80,58,1,False
11,Blastoise,9,Water,NaN,530,79,83,100,85,105,78,1,False
12,BlastoiseMega Blastoise,9,Water,NaN,630,79,103,120,135,115,78,1,False
13,Caterpie,10,Bug,NaN,195,45,30,35,20,20,45,1,False
14,Metapod,11,Bug,NaN,205,50,20,55,25,25,30,1,False
15,Butterfree,12,Bug,Flying,395,60,45,50,90,80,70,1,False
16,Weedle,13,Bug,Poison,195,40,35,30,20,20,50,1,False
17,Kakuna,14,Bug,Poison,205,45,25,50,25,25,35,1,False
18,Beedrill,15,Bug,Poison,395,65,90,40,45,80,75,1,False
19,BeedrillMega Beedrill,15,Bug,Poison,495,65,150,40,15,80,145,1,False
20,Pidgey,16,Normal,Flying,251,40,45,40,35,35,56,1,False
21,Pidgeotto,17,Normal,Flying,349,63,60,55,50,50,71,1,False
22,Pidgeot,18,Normal,Flying,479,83,80,75,70,70,101,1,False
23,PidgeotMega Pidgeot,18,Normal,Flying,579,83,80,80,135,80,121,1,False
24,Rattata,19,Normal,NaN,253,30,56,35,25,35,72,1,False
25,Raticate,20,Normal,NaN,413,55,81,60,50,70,97,1,False
26,Spearow,21,Normal,Flying,262,40,60,30,31,31,70,1,False
27,Fearow,22,Normal,Flying,442,65,90,65,61,61,100,1,False
28,Ekans,23,Poison,NaN,288,35,60,44,40,54,55,1,False
29,Arbok,24,Poison,NaN,438,60,85,69,65,79,80,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
136,Pinsir,127,Bug,NaN,500,65,125,100,55,70,85,1,False
137,PinsirMega Pinsir,127,Bug,Flying,600,65,155,120,65,90,105,1,False
138,Tauros,128,Normal,NaN,490,75,100,95,40,70,110,1,False
139,Magikarp,129,Water,NaN,200,20,10,55,15,20,80,1,False
140,Gyarados,130,Water,Flying,540,95,125,79,60,100,81,1,False
141,GyaradosMega Gyarados,130,Water,Dark,640,95,155,109,70,130,81,1,False
142,Lapras,131,Water,Ice,535,130,85,80,85,95,60,1,False
143,Ditto,132,Normal,NaN,288,48,48,48,48,48,48,1,False
144,Eevee,133,Normal,NaN,325,55,55,50,45,65,55,1,False
145,Vaporeon,134,Water,NaN,525,130,65,60,110,95,65,1,False
146,Jolteon,135,Electric,NaN,525,65,65,60,110,95,130,1,False
147,Flareon,136,Fire,NaN,525,65,130,60,95,110,65,1,False
148,Porygon,137,Normal,NaN,395,65,60,70,85,75,40,1,False
149,Omanyte,138,Rock,Water,355,35,40,100,90,55,35,1,False
150,Omastar,139,Rock,Water,495,70,60,125,115,70,55,1,False
151,Kabuto,140,Rock,Water,355,30,80,90,55,45,55,1,False
152,Kabutops,141,Rock,Water,495,60,115,105,65,70,80,1,False
153,Aerodactyl,142,Rock,Flying,515,80,105,65,60,75,130,1,False
154,AerodactylMega Aerodactyl,142,Rock,Flying,615,80,135,85,70,95,150,1,False
155,Snorlax,143,Normal,NaN,540,160,110,65,65,110,30,1,False
156,Articuno,144,Ice,Flying,580,90,85,100,95,125,85,1,True
157,Zapdos,145,Electric,Flying,580,90,90,85,125,90,100,1,True
158,Moltres,146,Fire,Flying,580,90,100,90,125,85,90,1,True
159,Dratini,147,Dragon,NaN,300,41,64,45,50,50,50,1,False
160,Dragonair,148,Dragon,NaN,420,61,84,65,70,70,70,1,False
161,Dragonite,149,Dragon,Flying,600,91,134,95,100,100,80,1,False
162,Mewtwo,150,Psychic,NaN,680,106,110,90,154,90,130,1,True
163,MewtwoMega Mewtwo X,150,Psychic,Fighting,780,106,190,100,154,100,130,1,True
164,MewtwoMega Mewtwo Y,150,Psychic,NaN,780,106,150,70,194,120,140,1,True
165,Mew,151,Psychic,NaN,600,100,100,100,100,100,100,1,False

In [9]:
# Rename the column headers
stats_transformed = stats_transformed.rename(columns={'Name': 'name',
                                                      '#': 'pokedex_index',
                                                      'Type 1': 'type_1',
                                                      'Type 2': 'type_2',
                                                      'Total': 'total',
                                                      'HP': 'hp',
                                                      'Attack': 'attack',
                                                      'Defense': 'defense',
                                                      'Sp. Atk': 'sp_attack',
                                                      'Sp. Def': 'sp_defense',
                                                      'Speed': 'speed',
                                                      'Generation': 'generation',
                                                      'Legendary': 'legendary'})
                
stats_transformed.head()

,name,pokedex_index,type_1,type_2,total,hp,attack,defense,sp_attack,sp_defense,speed,generation,legendary
0,Bulbasaur,1,Grass,Poison,318,45,49,49,65,65,45,1,False
1,Ivysaur,2,Grass,Poison,405,60,62,63,80,80,60,1,False
2,Venusaur,3,Grass,Poison,525,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,3,Grass,Poison,625,80,100,123,122,120,80,1,False
4,Charmander,4,Fire,NaN,309,39,52,43,60,50,65,1,False

### Export clean dataframe

In [10]:
stats_transformed.to_csv(output_data_file)